module.exports = {
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        primary: {
          400: "#A09001F",
          default: "#8F001A",
          500: "#8F001A",
          600: "#760015",
        },
        secondary: {
          100: "#f4eff9",
          200: "#eae0f3",
          300: "#8752be",
          400: "#562f7e",
          default: "#2f1a45",
          500: "#2f1a45",
          600: "#251537",
          700: "#1c0f29",
          800: "#120a1a",
        },
        tertiary: {
          100: "#dcd6e3",
          200: "#b4a7c4",
          300: "#9684ac",
          400: "#786392",
          default: "#5b4B6F",
          500: "#5b4b6f",
          600: "#483b58",
          700: "#352b40",
          800: "#211c29",
        },
      },
      fontFamily: {
        heading: [
          "Poppins",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: ["Georgia", "Cambria", '"Times New Roman"', "Times", "serif"],
        mono: [
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      spacing: {
        28: "6.5rem",
        92: "24rem",
        128: "32rem",
      },
      inset: {
        "-1": "-1px",
      },
      minHeight: (theme) => ({
        ...theme("spacing"),
      }),
      zIndex: {
        "-1": -1,
        100: 100,
      },
      boxShadow: {
        button: "inset 0 -3px 0 rgba(0, 0, 0, 0.2)",
      },
    },
  },
  variants: {},
  plugins: [],
  purge: false,
};
